#!/usr/bin/env python3

import psutil
import sys
import syslog
import yaml

config_file = '/etc/process_throttler.yaml'

try:
    with open(config_file) as fh:
        config = yaml.load(fh)
except:
    sys.stderr.write('Failed to load configuration from %s\n' % config_file)
    sys.exit(1)

for proc in psutil.process_iter():
    try:
        pinfo = proc.as_dict(attrs=['pid', 'name', 'username'])
    except psutil.NoSuchProcess:
        continue

    
